version: "3"

services:
  # Database
  postgres:
    image: postgres:15.2
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./postgres/database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pseudopass
      - POSTGRES_PASSWORD=pseudopass-default-password123
    networks:
      - pseudopass-network

  # Redis cache
  redis:
    image: "redis:6.0.12"
    ports:
      - "6379:6379"
    networks:
      - pseudopass-network

  # React app
  frontend:
    image: pseudopass-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../web/dist:/app/dist
      - ./certs:/etc/letsencrypt/live/pseudopass.org/
    networks:
      - pseudopass-network

  # Express.js app
  backend:
    restart: always
    ports:
      - "4443:4443"
    image: pseudopass-backend
    volumes:
      - ./dist:/app
    env_file: production.env
    environment:
      - ENV=production
    depends_on:
      - postgres
      - redis
    networks:
      - pseudopass-network
#   Certbot Let's Encrypt SSL Certificate
#  certbot:
#    image: certbot/certbot
#    command: certonly --webroot --webroot-path=/data/letsencrypt --email "michael.ruiz@sjsu.edu" --agree-tos --no-eff-email -d pseudopass.org -d api.pseudopass.org
#    volumes:
#      - ./data:/data/letsencrypt
#      - ./certs:/etc/letsencrypt
#    networks:
#      - pseudopass-network
#    depends_on:
#      - nginx

volumes:
  schemas:
    external: false

networks:
  pseudopass-network:
    driver: bridge